import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FooterWrapper from "@/components/FooterWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Central Gourmet",
  description: "Generated by R2CodeX",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="pt-BR"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
<body className="min-h-screen h-dvh flex flex-col bg-gray-900 text-white overflow-hidden">

  <main className="flex-1 overflow-y-auto pb-20">
    {children}
  </main>

        {/* FOOTER SEMPRE FIXO NO FINAL */}
        <FooterWrapper />
      </body>
    </html>
  );
}