import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FooterWrapper from "@/components/FooterWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Central Gourmet",
  description: "Generated by R2CodeX",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="pt-BR"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-screen flex flex-col overflow-hidden bg-gray-900 text-white">

        {/* CONTEÚDO */}
        <main className="flex-1 min-h-0 flex flex-col">
          {children}
        </main>

        {/* FOOTER GLOBAL */}
        <FooterWrapper />

      </body>
    </html>
  );
}